---
- name: Ensure we skip Rhel Enforcement
  include_tasks: ../common/skip_rhel_enforcement.yaml
  when: not ( enforce_rhel|bool )

- name: create pre-upgrade validation script for old version
  template:
    src: "pre-upgrade-osp13-validation.sh.j2"
    dest: "{{ working_dir }}/pre-upgrade-validation.sh"
    mode: 0775
    force: true

- name: create undercloud upgrade script
  template:
    src: "undercloud_upgrade.sh.j2"
    dest: "{{ working_dir }}/ffu_undercloud_upgrade.sh"
    mode: 0775
    force: true

- name: create ffu upgrade workaround scripts
  template:
    src: workarounds.sh.j2
    dest: "{{ working_dir }}/{{ item }}.sh"
    mode: 0775
    force: true
  loop:
    - 'pre_ffu_undercloud_os_upgrade_workarounds'
    - 'post_ffu_undercloud_os_upgrade_workarounds'
    - 'pre_ffu_undercloud_upgrade_workarounds'
    - 'post_ffu_undercloud_upgrade_workarounds'
