---
######## RHEL system upgrade ########
- name: apply pre ffu overcloud system upgrade workarounds in {{ host }}
  shell: |
    set -o pipefail
    ./pre_ffu_overcloud_os_upgrade_workarounds.sh \
      --limit {{ host }} 2>&1 {{ timestamper_cmd }} >> pre_ffu_overcloud_os_upgrade_workarounds_{{ host }}.log
  args:
    chdir: "{{ working_dir }}"
    executable: /usr/bin/bash
  when: ffu_upgrade_workarounds
  tags: ffu_overcloud_system_upgrade

- name: Disable scheduling on {{ host }}
  when:
    - compute_present|bool
  shell: |
    set -o pipefail
    source {{ overcloud_rc }}
    HOST="$(openstack compute service list -f value -c Host | grep {{ host }})"
    openstack compute service set --disable --disable-reason FFWD "$HOST" nova-compute

- name: run the pre upgrade script for the host {{ host }}
  when:
    - compute_present | bool
    - (workload_launch | bool) or (workload_external | bool)
  shell: |
    set -o pipefail
    ./{{ host }}_upgrade_pre.sh 2>&1 {{ timestamper_cmd }} >> {{ host }}_upgrade_pre.log
  args:
    chdir: "{{ working_dir }}"
    executable: /usr/bin/bash
  tags: ffu_overcloud_system_upgrade

- name: run the RHEL upgrade steps for the host {{ host }}
  shell: |
    set -o pipefail
    {{ overcloud_system_upgrade_script_base }}-{{ host }}.sh 2>&1 {{ timestamper_cmd }} >> \
        {{ overcloud_system_upgrade_script_base }}-{{ host }}.log
  args:
    chdir: "{{ working_dir }}"
    executable: /usr/bin/bash
  register: overcloud_system_upgrade_res
  ignore_errors: true
  tags: ffu_overcloud_system_upgrade

- name: was the RHEL upgrade step successful.
  fail: msg="Overcloud Operating System upgrade failed in {{ host }}."
  when: overcloud_system_upgrade_res.rc != 0
  tags: ffu_overcloud_system_upgrade

- name: apply post ffu overcloud system upgrade workarounds in {{ host }}
  shell: |
    set -o pipefail
    ./post_ffu_overcloud_os_upgrade_workarounds.sh --limit {{ host }} 2>&1 {{ timestamper_cmd }} >> \
        post_ffu_overcloud_os_upgrade_workarounds_{{ host }}.log
  args:
    chdir: "{{ working_dir }}"
    executable: /usr/bin/bash
  when: ffu_upgrade_workarounds
  tags: ffu_overcloud_system_upgrade

######## overcloud upgrade run ########
- name: Enable scheduling on {{ host }}
  when:
    - compute_present|bool
  shell: |
    set -o pipefail
    source {{ overcloud_rc }}
    HOST="$(openstack compute service list -f value -c Host | grep {{ host }})"
    openstack compute service set --enable "$HOST" nova-compute

- name: apply pre ffu overcloud upgrade workarounds in {{ host }}
  shell: |
    set -o pipefail
    ./pre_ffu_overcloud_upgrade_workarounds.sh --limit {{ host }} 2>&1 {{ timestamper_cmd }} >> \
        pre_ffu_overcloud_upgrade_workarounds_{{ host }}.log
  args:
    chdir: "{{ working_dir }}"
    executable: /usr/bin/bash
  when: ffu_upgrade_workarounds
  tags: ffu_overcloud_upgrade_run

# HACK for ffwd upgrade
- set_fact:
    upgrade_host: "{{ host + ',' + pcs_host }}"
- set_fact:
    pcs_host: "{{ upgrade_host | regex_replace(',$', '') }}"

- name: run overcloud major upgrade for the host {{ pcs_host if pcs_present else host }}
  shell: |
    set -o pipefail
    {{ overcloud_upgrade_run_script_base }}-{{ pcs_host if pcs_present else host }}.sh 2>&1 {{ timestamper_cmd }} >> \
        {{ overcloud_upgrade_run_script_base }}-{{ pcs_host if pcs_present else host }}.log
  args:
    chdir: "{{ working_dir }}"
    executable: /usr/bin/bash
  register: overcloud_upgrade_res
  ignore_errors: true
  tags: ffu_overcloud_upgrade_run

- name: was the overcloud upgrade composable step successful.
  fail: msg="Overcloud upgrade composable step failed for {{ host }}... :("
  when: overcloud_upgrade_res.rc != 0
  tags: ffu_overcloud_upgrade_run

- name: apply post ffu overcloud upgrade workarounds in {{ host }}
  shell: |
    set -o pipefail
    ./post_ffu_overcloud_upgrade_workarounds.sh --limit {{ host }} 2>&1 {{ timestamper_cmd }} >> \
        post_ffu_overcloud_upgrade_workarounds_{{ host }}.log
  args:
    chdir: "{{ working_dir }}"
    executable: /usr/bin/bash
  when: ffu_upgrade_workarounds
  tags: ffu_overcloud_upgrade_run
