---
- set_fact:
    pcs_host: ""

- name: upgrade the whole overcloud
  vars:
    host: "{{ item | reject('none') | join(',') }}"
    pcs_present: false
    compute_present: false
    oc_role_host_list: >-
      {{ (oc_roles_hosts|dict2items | default([])) |
           map(attribute='value') | map('sort') | flatten(1) }}
  include_tasks: overcloud_upgrade_hosts.yaml
  with_together: "{{ (oc_role_host_list | length == 0) | ternary([[], []], oc_role_host_list) + ['undercloud'] }}"
