- project:
    templates:
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-linters
    gate:
      queue: tripleo
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - publish-openstack-python-branch-tarball
