---
- name: stop l3 agent connectivity check
  shell: |
    source {{ overcloud_rc }}
    {{ l3_agent_connectivity_check_stop_script }} {{ current_stage_error|default(loss_threshold) }}
  when: l3_agent_connectivity_check
