---
- name: reboot the undercloud
  shell: "sleep 2 && shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true
  become: true
  become_user: root

- name: wait for node to go down
  become: false
  command: ping -c1 {{ ansible_host }}
  register: node_down
  until: node_down.rc != 0
  retries: 60
  delay: 3
  ignore_errors: true
  delegate_to: localhost
  when: "'hypervisor' not in groups and 'virthost' not in groups"

- name: wait for node to go down
  command: ping -c1 {{ ansible_host }}
  register: node_down
  until: node_down.rc != 0
  retries: 60
  delay: 3
  ignore_errors: true
  delegate_to: hypervisor
  when: "'hypervisor' in groups"

- name: wait for node to go down
  command: ping -c1 {{ ansible_host }}
  register: node_down
  until: node_down.rc != 0
  retries: 60
  delay: 3
  ignore_errors: true
  delegate_to: virthost
  when: "'virthost' in groups"

- name: waiting for the undercloud to be ssh-able
  wait_for_connection:
    connect_timeout: 5
    sleep: 3
    timeout: 900
