---
- name: Ensure Openvswitch is enabled and running
  service:
    name: openvswitch
    enabled: true
    state: started

- name: Update needed packages prior the undercloud upgrade
  package:
    name:
      - "{{ (ansible_python.version.major is version('3', '>=')) | ternary('python3-tripleoclient', 'python-tripleoclient') }}"
    state: latest

- name: get installed package fact
  package_facts:
    manager: "auto"

- name: Update Ceph Ansible prior upgrade
  package:
    name:
      - "ceph-ansible"
    state: latest
  when: "'ceph-ansible' in ansible_facts.packages"
