---
- name: Ensure Openvswitch is installed
  package:
    name: "{{ 'openvswitch' if use_oooq|bool else 'rhosp-openvswitch' }}"
    state: present

- name: Ensure Openvswitch is enabled and running
  service:
    name: openvswitch
    enabled: true
    state: started

- name: Update needed packages prior the undercloud upgrade
  package:
    name:
      - "{{ 'python-tripleoclient' if use_oooq|bool else 'python3-tripleoclient' }}"
      - "openstack-tripleo-common"
      - "openstack-tripleo-heat-templates"
    state: latest
