---
- name: Remove old RHEL7 packages
  # Remove all el7ost packages except those which could imply the removal
  # (direct or indirect) of the leapp and subscription-manager packages.
  shell: >-
     yum -y remove
     *el7ost*
     galera*
     haproxy*
     httpd
     mysql*
     pacemaker*
     python-jsonpointer
     qemu-kvm-common-rhev
     qemu-img-rhev
     rabbit*
     redis*
     --
     -*openvswitch*
     -python-docker
     -python-PyMySQL
     -python-pysocks
     -python2-asn1crypto
     -python2-babel
     -python2-cffi
     -python2-cryptography
     -python2-dateutil
     -python2-idna
     -python2-ipaddress
     -python2-jinja2
     -python2-jsonpatch
     -python2-markupsafe
     -python2-pyOpenSSL
     -python2-requests
     -python2-six
     -python2-urllib3

- name: Install leapp
  package:
    name:
      - leapp
      - leapp-repository
    state: latest
  when:
    - not leapp_unsubscribed|bool

- name: Get packages facts to obtain leapp's package version installed
  package_facts:
    manager: "auto"

- name: Get major leapp version
  set_fact:
    leapp_version: "{{ ansible_facts.packages.leapp[0].version }}"

- name: Download required leapp files
  vars:
    # Add master revision when latest leapp will be available.
    revision: "{{ '1405a623104fada7af29d8b0cb1ba5d7a821ea08' if leapp_version is version('0.9', '<') else 'master' }}"
  get_url:
    url: "https://gitlab.cee.redhat.com/leapp/oamg-rhel7-vagrant/raw/{{ revision }}/roles/init/files/leapp-data/{{ item }}"
    dest: "/etc/leapp/files/{{ item }}"
    validate_certs: false
    mode: '0700'
  loop:
    - 'pes-events.json'
    - 'repomap.csv'

- name: Check if rhos-release is installed
  package:
    name: rhos-release
    state: present
  check_mode: true
  failed_when: false
  register: rhos_release_installed

- block:
    - name: Remove rhos-release repos
      command: rhos-release -x

    - name: Remove conflicting rhos-release package
      package:
        name: rhos-release
        state: absent
  when:
    - not leapp_unsubscribed|bool
    - rhos_release_installed.rc == 0
    - not rhos_release_installed.changed

- name: Run leapp upgrade (download packages)
  shell: |
    set -o pipefail
    {% if leapp_unsubscribed|bool and (upgrade_workarounds|bool or ffu_upgrade_workarounds|bool) %} LEAPP_UNSUPPORTED=1 LEAPP_DEVEL_SKIP_RHSM=1 {% endif %}\
    {% if leapp_skip_release_check|bool %} LEAPP_SKIP_CHECK_OS_RELEASE=1 LEAPP_DEVEL_SKIP_CHECK_OS_RELEASE=1  {% endif %} sudo -E leapp upgrade --debug 2>&1 | \
        tee {{ working_dir }}/undercloud_leapp_upgrade.log

# Reboot, and wait for 30 mins
- name: Reboot the undercloud
  reboot:
    reboot_timeout: 1800

- name: Unregister the node once the OS was upgraded if desired
  redhat_subscription:
    state: absent
  when:
    - leapp_unregister|bool
    - not leapp_unsubscribed|bool
