---
- name: register latest installed kernel version
  shell: |
    rpm -qa | grep ^kernel-[0-9] | sort | tail -1 | awk -F 'kernel-' {'print $2'}
  register: installed_kernel

- name: register loaded kernel
  command: uname -r
  register: loaded_kernel

- name: register installed openvswitch package version
  shell: |
    rpm --queryformat %{VERSION} -q openvswitch | awk -F "." '{print $1"."$2}'
  register: installed_ovs

- name: register loaded openvswitch version
  shell: |
    ovs-vsctl show | grep ovs_version | awk -F \" {'print $2'} | awk -F "." '{print $1"."$2}'
  become: true
  become_user: root
  register: loaded_ovs

- name: handle undercloud reboot
  block:
    # Reboot, and wait for 30 mins
    - name: Reboot the undercloud
      reboot:
        reboot_timeout: 1800
      become: true
      become_user: root

    - name: assert UC services started
      shell: |
        source {{ undercloud_rc }}
        timeout 10 openstack endpoint list
      ignore_errors: true
      retries: "{{ service_readiness_count|default(100)|int }}"
      delay: 3
  when:
    - not tripleo_ci
    - >
      undercloud_reboot or
      (installed_kernel.stdout != loaded_kernel.stdout) or
      (installed_ovs.stdout != loaded_ovs.stdout)
  tags: undercloud_reboot
